### ISSUE TITLE
Expand t.co URLs

### ISSUE THREAD

**Issue by Lewiscowles1986** [edent/Tweet2Img#2]
I don't know if melon husk has had it changed; but t.co urls' used to be trivially resolvable using CURL to follow a link.

I Believe it is `curl --head $URL|grep Location|awk '{print $2}'`

If you have any current t.co links, and can share them here, I'd be happy to try it out.

I Think they also might be trivially regex friendly, because of the silly shortened path.

**Comment by edent** [comment]
They are already expanded in the semantic HTML version.

**Comment by Lewiscowles1986** [comment]
So it's just the alt text? Sorry I'm asking because I read your README; I am not a twitter or X user.

**Comment by edent** [comment]
Probably best if you run the code and then report any issues you fine.
